Module4 task3
htmlacademy-nodejs/780911-typoteka-3 pull request #13
Opened 2021-07-03 18:05 UTC by ChloeSilent

Task: https://up.htmlacademy.ru/nodejs/3/tasks/25

2021-07-18 19:34 UTC, balesniy requested changes
- модулям и шаблонам нужно дать более наглядные названия
- в шаблонах нужно навести порядок: использовать наследование
- реализовать простейшую валидацию данных от пользователя

2021-07-18 19:34 UTC, balesniy commented on src/express/middlewares/validator.js
> +const URL_ARTICLES = `http://localhost:3000/api/articles/`;
повторяется в модулях, выноси в настройки

2021-07-18 19:34 UTC, balesniy commented on src/express/templates/404.pug
> +    link(rel='preload' href='/fonts/Inter-Regular.woff2' as='font' crossorigin='anonymous')
имеет смысл вынести общий для страниц layout, см https://pugjs.org/language/inheritance.html

2021-07-18 19:34 UTC, balesniy commented on src/express/templates/admin-add-new-post-empty.pug
> +                        input#new-publication-date(type='text' placeholder=`${article.date}`)
Проверьте наличие атрибутов name у полей формы.

2021-07-18 19:34 UTC, balesniy commented on src/express/templates/admin-comments.pug
> +                 b.publication__list-name Александр Петров
рыба осталась

2021-07-18 19:34 UTC, balesniy commented on src/routes/articles.js
> +const adminAddNewPostEmpty = require(`./admin-add-new-post-empty`);
модулям можно дать более наглядные названия

2021-07-18 19:34 UTC, balesniy commented on src/routes/search.js
> +searchRouter.get(`/`, async (req, res) => {
async без await лишний

2021-07-18 19:34 UTC, balesniy commented on src/routes/search.js
> +  } catch (error) {
этот catch ничего не ловит

2021-07-18 19:34 UTC, balesniy commented on src/routes/admin-add-new-post-empty.js
> +    res.render(`admin-add-new-post-empty`, {article: emptyPost, type});
Форма должна быть заполнена введёнными данными.

2021-07-18 19:34 UTC, balesniy commented on src/routes/articles-edit-articleId.js
> +editArticleByIdRoute.put(`/:articleId`, (req, res) => {
11.2. Правила валидации соответствуют аналогичным для страницы «Новая публикация;

2021-07-21 18:02 UTC, ChloeSilent commented on src/express/templates/404.pug
> +    link(rel='preload' href='/fonts/Inter-Regular.woff2' as='font' crossorigin='anonymous')
вынесено

2021-07-21 18:06 UTC, ChloeSilent commented on src/express/templates/admin-add-new-post-empty.pug
> +                        input#new-publication-date(type='text' placeholder=`${article.date}`)
добавлено, тем у кого нет или неверно указано

2021-07-22 17:49 UTC, ChloeSilent commented on src/express/templates/admin-comments.pug
> +                 b.publication__list-name Александр Петров
удалила

2021-07-22 17:50 UTC, ChloeSilent commented on src/routes/articles.js
> +const adminAddNewPostEmpty = require(`./admin-add-new-post-empty`);
переименованы

2021-07-22 17:58 UTC, ChloeSilent commented on src/routes/search.js
> +  } catch (error) {
убрала

2021-07-22 18:11 UTC, ChloeSilent commented on src/routes/admin-add-new-post-empty.js
> +    res.render(`admin-add-new-post-empty`, {article: emptyPost, type});
пофиксила

2021-07-22 18:40 UTC, ChloeSilent commented on src/routes/articles-edit-articleId.js
> +editArticleByIdRoute.put(`/:articleId`, (req, res) => {
добавила

2021-07-27 14:23 UTC, balesniy approved these changes

2021-07-27 14:23 UTC, balesniy commented on src/express/index.js
> +      console.log(`Error: ${err.message}`);
кроме лога нужно показать ошибку пользователю

2021-07-27 14:23 UTC, balesniy commented on src/express/templates/my-comments.pug
> +        ul.navigation.header__navigation
общую часть можно вынести в отдельный шаблон, чтобы не "шумело" и правки было удобно вносить

2021-07-27 14:23 UTC, balesniy commented on src/express/templates/sign-in-error-2.pug
> +    link(rel='preload' href='/fonts/Inter-Regular.woff2' as='font' crossorigin='anonymous')
повторяет sign-in-error-1.pug - общую часть шаблонов лучше вынести

2021-07-27 14:23 UTC, balesniy commented on src/routes/article-add.js
> +        .then(() => {
в async функции удобно пользоваться await и читаться будет лучше

2021-07-27 14:23 UTC, balesniy commented on src/routes/search.js
> +          item.formattedDate = formatDateForPug(item.createdDate);
повторяющуюся логику обработки запроса можно вынести в мидлвар

2021-07-27 14:23 UTC, merged